name: hyrega
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004607'
    - '#c3c1cf'
    - '#b0205b'
    - '#b16886'
    - '#a29295'
  brandStrength: 0.8033703002147377
  lightness: 0.7982206107117236
  saturation: 0.05736588151194155
  rhythmicContrast: 0.32143952208571136
purpose: []
