name: hyrega
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63801
title: HYPER REALITY GALLERY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebece7'
    - '#cbcdc8'
    - '#a17f52'
    - '#b2b4b1'
    - '#906c39'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
