name: hyrega
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63801
title: HYPER REALITY GALLERY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004607'
    - '#c3c1cf'
    - '#b0205b'
    - '#b16886'
    - '#a29295'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
