name: hyrega
favicon: null
layout_spectrum: 0.00826
typography_spectrum: 0.63801
title: HYPER REALITY GALLERY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6ecf8'
    - '#787471'
    - '#969a99'
    - '#454449'
    - '#1e1c27'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
